[package]
name = "stonetr03/debug-module"
description = "Debug Lines"
version = "2.0.0"
license = "gpl-3.0"
authors = ["Stonetr03"]
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"

exclude = ["Images","test","foreman.toml","test.project.json"]
include = ["src","default.project.json","wally.toml","wally.lock","LICENSE"]

[dependencies]
Fusion = "elttob/fusion@0.2.0"